# Generated by Django 5.0 on 2024-01-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
